version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                user: agung
                uid: 1000
        image: pec-auth-services:1.0
        container_name: pec-auth-services
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - authservices
    db:
        image: mysql:8.3
        container_name: db-pec-auth
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - authservices
    nginx:
        image: nginx:alpine
        container_name: web-server-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - authservices

networks:
    authservices:
        driver: bridge
